### ISSUE TITLE
点赞怎么能像今日头条那样消失前渐隐动画呢

### ISSUE THREAD

**Issue by caprice** [Qiu800820/SuperLike#2]
感谢作者提供了思路. 看了今日头条，网易的动画最后都是渐隐消失的，你这个最后没有这个功能，我该如何扩展达到这个目的呢。谢谢！

**Comment by Qiu800820** [comment]
Element添加一个透明度的方法即可， 可能会修改到源码。后面可以弄一个AnimationFrameFactory 方便扩展自定义动画

**Comment by caprice** [comment]
目前是这么做的，应该和你思路一样：


       @Override
        public int getAlpha() {
            return alpha;
        }

        @Override
        public Bitmap getBitmap() {
            return bitmap;
        }

        @Override
        public void evaluate(int start_x, int start_y, double time) {
            time = time / 800;
            //当前点的时间小于总时间800的65%时，不透明
            if(time < 0.65){
                alpha = 255;
            }else{
                //超过65%时，透明度逐渐加大
                alpha = (int)(255 * (1- time));
            }
            double x_speed = speed * Math.cos(angle * Math.PI / 180);
            double y_speed = -1.5*speed * Math.sin(angle * Math.PI / 180);
            x = (int)(start_x + (x_speed * time)  - (bitmap.getWidth() / 2));
            y = (int)(start_y + (y_speed * time) + (GRAVITY * time * time) / 2 - (bitmap.getHeight() / 2));
        }

**另外，还差一个长按不断喷射，就完美了**
