### ISSUE TITLE
你好,你觉得从产品上考虑,这个点赞特效有什么用

### ISSUE THREAD

**Issue by ayyb1988** [Qiu800820/SuperLike#3]

**Comment by Qiu800820** [comment]
点赞\取消点赞需要调用服务器接口，一般为了防止用户重复点击造成服务器响应点赞\取消点赞乱序，都会做点击事件的防抖，但只在代码中过滤一段时间内重复的点击事件，没有界面交互体验不好，所以就有了这个库。
